name: MediaWarp Docker Builder

on:
  workflow_call:
    inputs:
      APP_VERSION:
        description: "用于Docker镜像版本的标签号"
        required: true
        type: string
      IS_LATEST:
        description: "是否发布为Docker镜像最新版本"
        required: true
        type: boolean

env:
  APP_VERSION: ${{ inputs.APP_VERSION }}
  IS_LATEST: ${{ inputs.IS_LATEST }}

jobs:
  docker-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Show Information
        run: |
          echo "Docker镜像版本的标签号：${{ env.APP_VERSION }}"
          echo "是否发布为Docker镜像最新版本：${{ env.IS_LATEST }}"

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/mediawarp
          tags: |
            type=raw,value=latest,enable=${{ env.IS_LATEST }}
            type=raw,value=${{ env.APP_VERSION }},enable=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
            linux/s390x
          push: true
          build-args: |
            MEDIAWARP_VERSION=${{ env.APP_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}-docker
          cache-to: type=gha, scope=${{ github.workflow }}-docker
